### ISSUE TITLE
Get logo with colored "O"

### ISSUE THREAD

**Issue by gmittal** [TotalityHacks/totality-landing#3]
I think the current logo is pretty nice, but given the black background and white text, it might be nice to add some flare by using the redish "O" (like the one on the GitHub organization page) in place of the white O in ```logo.svg```.

Just a suggestion.

**Comment by jasonscharff** [comment]
@gmittal In the google drive folder there is a folder called assets which has it.

**Comment by gmittal** [comment]
Do we have a white version with the red O? I can't seem to find it in the folder.

**Comment by jasonscharff** [comment]
@gmittal Not ready-made, but it's not too hard to make because the raw AI files are in there.

**Comment by gmittal** [comment]
I don't have AI, if you could add it to the folder I'd really appreciate it.

**Comment by jasonscharff** [comment]
Will do. Not able to do it quite this second so just use a placeholder for now, but I can get it later tonight.

**Comment by gmittal** [comment]
No worries. Just ping me when you get the chance to finish it so I can add it in.

**Comment by jasonscharff** [comment]
@gmittal Done. let me know if there are issues with it.

**Comment by gmittal** [comment]
Fixed
