### ISSUE TITLE
Clean up styles and fonts

### ISSUE THREAD

**Issue by gmittal** [TotalityHacks/totality-landing#6]
From @jasonscharff:

1. Not a huge fan of the font. I think the logo goes for cleaner sort of look, but the font and the dollar sign in front of the sections looks more "code like." I prefer the cleaner look. The font in the logo is Ubuntu from google fonts. Love the new white logo with red sun BTW.
2. I'd like to add some sort of navigation bar as it could get difficult to follow with real content
3. Add a sponsor section––For now I'll just add something like for info on sponsoring email sponsor@totalityhacks.com
4. The copyright should actually be "Hackathon Organizers, LLC"
5. I think we should shrink the footer––and not have links to things that don't exist.
6. I'd like more distinction between the sections through different backgrounds or something. It can get hard to read in long form.

**Comment by gmittal** [comment]
1, 3, 4 are done.

**Comment by jasonscharff** [comment]
@gmittal Changes look great thus far. One more change is we need to add a way for people to contact us with questions––the email is hello@totalityhacks.com.

I'm working on content now. I won't commit the content until this is done to avoid any conflicts, but it should be done within the next couple days-–aiming for by the end of this weekend though.

**Comment by gmittal** [comment]
You can also send me the content and I can commit it in, if that works for you.

**Comment by gmittal** [comment]
5, 6, done.

**Comment by gmittal** [comment]
Also it doesn't seem like there's any really easy way to add a nice navbar without drastically changing a lot of the CSS. Let's file a separate issue for navbar, and we can add it in when it actually becomes necessary. Right now there aren't that many pages.

**Comment by jasonscharff** [comment]
@gmittal If you link to the MLH CoC, it'll be good to push once I add content. I also created an issue (https://github.com/TotalityHacks/totality-landing/issues/10) that is less urgent, but we should also link FB/Twitter/Medium/Github on the bottom (we can also replace the email in text and put it there).

**Comment by jasonscharff** [comment]
@gmittal I added some content to the website. It's not final, but generally what I was thinking in that sense.

**Comment by gmittal** [comment]
Alright. Should we merge?

**Comment by jasonscharff** [comment]
@gmittal Fix the CoC issue first, then go ahead. There are definitely a few issues still I think (and I'd like @jreinstra to take a look at the content) that need to be addressed, but this is overall much better.
